### PR TITLE
Add fluxProvider.useEvalAsync()

### LINKED ISSUE #66: Some $listenTo callbacks run outside of the digest cycle when Baobao is in asynchronous mode
I've been chasing down a bug with directives not updating with flux-angular, and I think the root cause of the problem is that baobao's asynchronous mode does not work well with Angular's digest cycle.

This is in a fairly complex app, so it will be hard to make a test case, but basically I have something like this:

``` js
function updateFilterDescriptionFromStore () {
   console.log('$rootScope.$$phase: ' + $rootScope.$$phase);
   $scope.filterDescription = _.keys(MyStore.getFilter()).join(', ');
}

$scope.$listenTo(MyStore, ['filter'], updateFilterDescriptionFromStore);
```

When I change the `filter` cursor through other parts of the app (using `flux.dispatch`), I get this in the console:

```
$rootScope.$$phase: $digest
$rootScope.$$phase: $digest
$rootScope.$$phase: null
```

Sometimes it is called in a digest cycle and sometimes it isn't.

I think what is going on here is that when baobao is in `asynchronous: true` mode, it is waiting to emit the `update` event (which then calls the `$listenTo` callback) until the next browser tick. It does this with `setTimeout(() => this.commit(), 0)` [here](https://github.com/Yomguithereal/baobab/blob/9c8765a57093ca7823f05450674ec8b4b5e66b21/src/baobab.js#L443).

Sometimes `this.commit()` is called while a digest cycle is happening, and sometimes it isn't.

I know I could disable async mode, but it makes things much faster when there are many updates to the store at once.

What I ended up doing is wrapping all of my `$scope.$listenTo` callbacks in `$scope.$asyncApply` like this:

``` js
function updateFilterDescriptionFromStore () {
   $scope.$asyncApply(function () {
      console.log('$rootScope.$$phase: ' +$rootScope.$$phase);
      $scope.filterDescription = _.keys(MyStore.getFilter()).join(', ');
   });
}

$scope.$listenTo(MyStore, ['filter'], updateFilterDescriptionFromStore);
```

That seems to fix the issue, but it is awkward and easy to forget to do that.

Is there a better way to fix this problem? Alternatively, I could attempt to make a PR that calls the `$listenTo` callbacks in `$scope.$applyAsync` automatically. What do you think of that solution?

### PR DESCRIPTION
**Pull request by afiedler**
Adds an optional setting to `fluxProvider` to cause the `flux` service to wrap all `$scope.$listenTo` callbacks in `$scope.$applyAsync`.

This fixes #66, where in some cases the `$listenTo` callbacks were getting called outside of the digest cycle.

This is inspired by the `useApplyAsync` option in the [`$http` service in Angular](https://docs.angularjs.org/api/ng/provider/$httpProvider).

### CODE REVIEW

**Comment by Guria** [comment]
Unfortunately this repo is unmantained now, since @christianalfoni not interested in it.
Now we actively support only cerebral-js which is view agnostic. But unfortunately have no angular implementations for cerebral v2 since we don't have much demands on it.

Feel free to start a fork or ask @christianalfoni to transfer repo maintainance.

**Comment by jrust** [comment]
@Guria I'm still using it heavily and @christianalfoni gave me repo rights a while ago. If it'd be better to have repo transferred entirely let me know.

**Comment by jrust** [comment]
@afiedler code looks good.  Curious if you think `true` should be the default and if it appears to change performance at all?

**Comment by Guria** [comment]
@jrust oh, sorry for misinformation. Glad that there is active maintainer here.

**Comment by jrust** [comment]
No problem @Guria 

@afiedler just saw your comment on the other issue on speed.  Tried it out locally and the `applyAsync` was causing errors because it was batching the changes up until 10ms later which led to some timing issues.  However, switching to `evalAsync` did clear up most of those and didn't exhibit any slowdown.  There are still a few strange behaviors when dealing with animations, but that could be something strange we're doing.  Does `evalAsync` work for you?

**Comment by afiedler** [comment]
@jrust, yeah I just tested it with $evalAsync on my project and that works fine. I pushed two commits that make the change to this PR.

I'm not sure about the default. It seems like this is the "proper" way to do it. The issue is that baobab [runs its callbacks in a `window.setTimeout`](https://github.com/Yomguithereal/baobab/blob/9c8765a57093ca7823f05450674ec8b4b5e66b21/src/baobab.js#L443), which means they may or may not run as part of the digest cycle. So this fixes that problem. But I'm not sure if doing this would cause anyone any issues that depended on the previous behavior.

I guess I'll leave the decision on the default up to you 😄 . As long as I don't have to litter my code with `$evalAsync`, I'm a happy camper.

**Comment by jrust** [comment]
I agree. I think its saner and safer behavior to be default true.  If you can make it true by default I'll merge it in and make a release

**Comment by afiedler** [comment]
@jrust, I changed the default of `useEvalAsync` to true and updated the specs and README.

**Comment by jrust** [comment]
Looks great, thanks for your work on this.

**Pull request merged**
